# Generated by Django 6.0.3 on 2026-05-01 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('imei_serial', models.CharField(max_length=50, unique=True, verbose_name='IMEI ou Serial')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='blog.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeito_relatado', models.TextField()),
                ('laudo_tecnico', models.TextField(blank=True, null=True)),
                ('valor_orcamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('manutencao', 'Em Manutenção'), ('finalizada', 'Finalizada/Pronta'), ('entregue', 'Entregue ao Cliente'), ('descarte', 'Destinado ao Descarte')], default='aberta', max_length=20)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dispositivo')),
            ],
        ),
    ]
