# Generated by Django 6.0.3 on 2026-05-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cliente_dispositivo_ordemservico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
